server:
  port: 80
spring:
  application:
    # 服务别名
    name: consul-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.244.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}
