server:
  port: 8006
spring:
  application:
    # 服务别名---注册consul到注册中心的名称
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.244.129:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.244.129
      port: 8500
      discovery:
#        hostname: 127.0.0.1
        service-name: ${spring.application.name}