server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.244.129:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    #将自己注册进注册中心
    register-with-eureka: true
    #是否检索自己的服务
    fetch-registry: true
    service-url:
      #注册中心地址
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #修改服务名称 actuator服务信息完善
    instance-id: payment8001
    #显示IP地址
    prefer-ip-address: true
    #client多久向服务端发送心跳 默认30S
    lease-renewal-interval-in-seconds: 1
    #server没收到心跳后的等待时间 默认90S
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tl.springcloud.entities